In [ ]:
a=[34,56,11,33]
b=sorted(a)
print(a)
print(b)

[34, 56, 11, 33]
[11, 33, 34, 56]


In [ ]:
a=(45,66,90,1,10)
b=sorted(a)
print(b)

[1, 10, 45, 66, 90]


In [ ]:
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B = np.linspace(1,13,12).reshape(2,6)
print(B)

[[ 1.          2.09090909  3.18181818  4.27272727  5.36363636  6.45454545]
 [ 7.54545455  8.63636364  9.72727273 10.81818182 11.90909091 13.        ]]


In [ ]:

C= np.array([12,34,562,36,37,67,45,78])
C.resize(2,2,2)
#changes the shape of original array
#reshape - changes needs saving in another variable
print(C)

[[[ 12  34]
  [562  36]]

 [[ 37  67]
  [ 45  78]]]


In [ ]:
A = np.array([12,54,78,90])#list will throw an error while arrays iterate themselves
B = np.array([2,56,67,89])
print(A-B)
print(A+B)

[10 -2 11  1]
[ 14 110 145 179]


In [ ]:
A = np.array([23,56,78,98,55,11]).reshape(2,3)
B = np.array([89,43,52,90,12,66]).reshape(2,3)
print(A)
c=('______________________')
print(c)
print(B)
print(c)
C = A*B # * is a one on one multiplication
print(C)

[[23 56 78]
 [98 55 11]]
______________________
[[89 43 52]
 [90 12 66]]
______________________
[[2047 2408 4056]
 [8820  660  726]]


In [ ]:
A = np.array([23,56,78,98,55,11]).reshape(2,3)
B = np.array([89,43,52,90,12,66]).reshape(3,2)
print(A)
c=('______________________')
print(c)
print(B)
print(c)
C = A@B # matrix multiplication
print(C)

[[23 56 78]
 [98 55 11]]
______________________
[[89 43]
 [52 90]
 [12 66]]
______________________
[[ 5895 11177]
 [11714  9890]]


In [ ]:
A = np.array([34,67,89,28,91])
print(A.max())
print(A.min())

91
28


In [ ]:
A = np.array([23,56,78,98,55,11]).reshape(2,3)
B = np.array([89,43,52,90,12,66]).reshape(3,2)
print(A)
c=('______________________')
print(c)
print(B)
print(c)
C = A.dot(B) # matrix multiplication
print(C)

[[23 56 78]
 [98 55 11]]
______________________
[[89 43]
 [52 90]
 [12 66]]
______________________
[[ 5895 11177]
 [11714  9890]]


In [ ]:
 A = np.array([23,56,78,98,55,221,33,44,66,77,88,99]).reshape(3,4)
 c=('_____________________________')
 print(A)
 print(c)
 print(A.min(axis=0)) # axis 0 - column
 print(c)
 print(A.max(axis=1)) #ais 1 - row
 print(c)
 print(A.min(axis=0))
 print(c)
 print(A.min(axis=1))

[[ 23  56  78  98]
 [ 55 221  33  44]
 [ 66  77  88  99]]
_____________________________
[23 56 33 44]
_____________________________
[ 98 221  99]
_____________________________
[23 56 33 44]
_____________________________
[23 33 66]


In [ ]:
A = np.array([23,56,78,98,55,221,33,44,66,77,88,99]).reshape(3,4)
B = np.array([9,81,18.63,36,72,27,54,45,1,59,95,88]).reshape(3,4)
print("After Vertically stacking arrays!")
print(np.vstack((A,B)))

print(c)
print("After horizantally stacking arrays!")
print(np.hstack((A,B)))

After Vertically stacking arrays!
[[ 23.    56.    78.    98.  ]
 [ 55.   221.    33.    44.  ]
 [ 66.    77.    88.    99.  ]
 [  9.    81.    18.63  36.  ]
 [ 72.    27.    54.    45.  ]
 [  1.    59.    95.    88.  ]]
_____________________________
After horizantally stacking arrays!
[[ 23.    56.    78.    98.     9.    81.    18.63  36.  ]
 [ 55.   221.    33.    44.    72.    27.    54.    45.  ]
 [ 66.    77.    88.    99.     1.    59.    95.    88.  ]]


In [ ]:
A = np.arange(12).reshape(2,3,2)
print(A)
print(c)
print("After d stack")
print(np.dstack(A)) #no.of rows --> no.of groups
#no.of col in every group --> no.of rows in a array
# original -> g- 2,r-3, c-5
#dstack -> g->3, r->5 ,c ->2


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
_____________________________
After d stack
[[[ 0  6]
  [ 1  7]]

 [[ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]]]


In [ ]:
A = np.arange(30).reshape(5,6)
print(A)
print("After spliting")
np.vsplit(A,5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
After spliting


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]])]

In [ ]:
A = np.arange(30).reshape(5,6)
print(A)
print("After spliting")
print(c)
np.vsplit(A,(1,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
After spliting
_____________________________


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]])]

In [ ]:
A = np.arange(30).reshape(5,6)
print(A)
print("After spliting")
np.hsplit(A,2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
After spliting


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29]])]

In [ ]:
A = np.arange(30).reshape(5,6)
print(A)
print("After spliting")
np.hsplit(A,(2,3,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
After spliting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [ ]:
D= np.array([23,34,45,67,78,89,90,12]).reshape(2,4)
print(D)
print(D.argmax(axis=0))
print(D.argmax(axis=1))

[[23 34 45 67]
 [78 89 90 12]]
[1 1 1 0]
[3 2]


In [ ]:
D= np.array([23,34,45,67,78,89,90,12]).reshape(2,4)
print(D)
print(D.argmin(axis=0))
print(D.argmin(axis=1))

[[23 34 45 67]
 [78 89 90 12]]
[0 0 0 1]
[0 3]


In [ ]:
#mean median std and variance
A=np.array([11,22,33,44,55,66,77])
print("Mean:",np.mean(A)) #mean = sum of no. of observations / no. of observations
print("Median:",np.median(A))
print("Variance:",np.var(A))
print("Standard deviation:",np.std(A))


Mean: 44.0
Median: 44.0
Variance: 484.0
Standard deviation: 22.0


In [ ]:
E = np.pi
print(E)  # radians



3.141592653589793


In [ ]:
np.rad2deg(E)


180.0

In [ ]:

E = [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(E)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
E = [np.pi/4,np.pi/3,np.pi/2,np.pi]

print(np.rad2deg(E))

[ 45.  60.  90. 180.]


In [ ]:
F = np.array([0,45,60,90,180])
print(np.rad2deg(F))

[    0.          2578.31007809  3437.74677078  5156.62015618
 10313.24031235]


In [ ]:
np.sin(F)

array([ 0.        ,  0.85090352, -0.30481062,  0.89399666, -0.80115264])

In [ ]:
np.cos(F)

array([ 1.        ,  0.52532199, -0.95241298, -0.44807362, -0.59846007])

In [ ]:
np.tan(F)

array([ 0.        ,  1.61977519,  0.32004039, -1.99520041,  1.33869021])

In [ ]:
np.arcsin(1)

1.5707963267948966

In [ ]:
np.arccos(1)

0.0

In [ ]:
np.arctan(1)

0.7853981633974483

In [ ]:
a=45
b=23
print(np.hypot(a,b)) #hypotenuse

50.53711507397311


In [ ]:
#searching of array
G = np.array([12,39,41,53,69])
print(np.where(G==41))

(array([2]),)


In [ ]:
print(np.where(G>=45))
print(np.where(G!=32))
print(np.where(G%2==0))

(array([3, 4]),)
(array([0, 1, 2, 3, 4]),)
(array([0]),)


In [7]:
import numpy as np
A = np.array([90,56,34,21,32,21])
print(np.searchsorted(A,56))          #outputs the index of the sorted element

6


LINEAR ALGEBRA AND UNIVERSAL FUNCTION


In [10]:
A =np.array([49,14,28,35,42])
B =np.array([24,16,40,56,8])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.divmod(A,B))

[73 30 68 91 50]
[ 25  -2 -12 -21  34]
[2.04166667 0.875      0.7        0.625      5.25      ]
[ 1 14 28 35  2]
(array([2, 0, 0, 0, 5]), array([ 1, 14, 28, 35,  2]))


In [13]:
print(np.sort(A))

[14 28 35 42 49]


In [15]:
print(np.diff(B))

[ -8  24  16 -48]


In [16]:
A =np.array([6,24,60,12,18])
B =np.array([6,4,10,5,4])
print(np.union1d(A,B))

[ 4  5  6 10 12 18 24 60]


In [17]:
A =np.array([6,24,60,12,18])
B =np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 18 24 60]


In [18]:
A =np.array([6,24,60,12,18])
B =np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[6]


ROUND FUNCTION

In [19]:
a1= np.trunc([-3.1666,3.6667])
print(a1)

[-3.  3.]


In [20]:
#rounding
a1= np.fix([-3.1666,3.6667])
print(a1)

[-3.  3.]


In [21]:
a1= np.around([3.16636,4])
print(a1)

[3. 4.]


In [22]:
a1= np.floor([-3.1666,3.6667])
print(a1)

[-4.  3.]


In [23]:
a1= np.ceil([-3.1666,3.11])
print(a1)

[-3.  4.]


In [25]:
A = np.array([3.456,2.789,-1,32.89057])
print(np.trunc(A))
print(np.fix(A))
print(np.floor(A))
print(np.ceil(A))
print(np.around(A))




[ 3.  2. -1. 32.]
[ 3.  2. -1. 32.]
[ 3.  2. -1. 32.]
[ 4.  3. -1. 33.]
[ 3.  3. -1. 33.]


In [27]:
A = np.array([3,45,2,8,9,15])
B = np.cumsum(A)
print(B)

[ 3 48 50 58 67 82]


In [28]:
print(np.lcm(34,56))
print(np.gcd(445,625))

952
5


In [29]:
Ar=np.array([45,65,75,85])
print(np.gcd.reduce(Ar))

5


In [30]:
Ar=np.array([45,65,75,85])
print(np.lcm.reduce(Ar))

49725


In [32]:
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


Random

In [34]:
from numpy import  random as rd

In [35]:
A = rd.rand()      #default limit is 0 to 0.99
print(A)

0.9218347880740168


In [38]:
A = rd.randint(4)    #syntax:andint(limit)==> limit 0,1,2,3,4,
print(A)

0


In [39]:
A = rd.randint(50,size=6)
print(A)

[ 4  6 24  6 30 35]


In [41]:
A = rd.randint(50,size=(2,3))
print(A)

[[42  9 49]
 [23 37  8]]


In [44]:
A = np.array([1,2,3])
B = np.array([4,5,6])
#1*4+2*5+3*6
print(np.inner(A,B))
# 1*(4,5,6) 2*(4,5,6) 3*(4,5,6)
print(np.outer(A,B))
#
print(np.cross(A,B))

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]
