In [ ]:
#variable at string
a=10
print("Iam",a,"years old")

Iam 10 years old


In [ ]:
#List comprehension
#newlist = [(st of if) if (cond) else (st of else) for]
l1=[23,67,12,34,69]
res=[i*i if i>50 else 'x' for i in l1]
print(res)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#arthematic operation of two numbers
a=int(input("enter a value:"))
b=int(input("enter b value:"))
print("Sum is:",a+b)
print("difference is:",a-b)
print("product is:",a*b)
print("quotient is:",a/b)
print("remainder is:",a%b)
print("power os a to be is:",a**b)
print("floor division is:",a//b)


enter a value:45
enter b value:7
Sum is: 52
difference is: 38
product is: 315
quotient is: 6.428571428571429
remainder is: 3
power os a to be is: 373669453125
floor division is: 6


In [ ]:
#take a number from the user which is a salary ,if the salary is >50000 there is a 10% tax print his final salary
salary=int(input("Enter salary:"))
if(salary>=50000):
  salary=salary-(salary*0.1)
  print("final salry is:",salary)
else:
  print("your salary is less than 50000 so no tax  ")

Enter salary:5
your salary is less than 50000 so no tax  


In [ ]:
#get the salary from the user if the salary is more than or equal 50000 apply 10% tax deduction , if the salary is lessthan 50000 apply 5% tax,if the salary is more than 70000 apply 12% tax,if the salary exceeds 1L you are promoted to next level
salary=int(input("Enter salary"))
if(salary==0):
  print("give valid salary")
elif(salary<=50000):
  salary=salary-(salary*(5/100))
  print("your salary is:",salary)
elif(salary<=70000):
  salary=salary-(salary*(10/100))
  print("your salary is:",salary)
elif(salary<=100000):
  salary=salary-(salary*(12/100))
  print("your salary is:",salary)
else:
  print("your promoted to next level")

Enter salary0
give valid salary


In [ ]:
from builtins import range
ran=range(1,11)
n=int(input("enter n value:"))
for i in ran:
  print(n,"*",i,"=",n*i)

enter n value:143
143 * 1 = 143
143 * 2 = 286
143 * 3 = 429
143 * 4 = 572
143 * 5 = 715
143 * 6 = 858
143 * 7 = 1001
143 * 8 = 1144
143 * 9 = 1287
143 * 10 = 1430


In [ ]:
n=int(input("enter n value:"))
i=1
while(i<11):
  print(n,"*",i,"=",n*i)
  i=i+1

enter n value:34
34 * 1 = 34
34 * 2 = 68
34 * 3 = 102
34 * 4 = 136
34 * 5 = 170
34 * 6 = 204
34 * 7 = 238
34 * 8 = 272
34 * 9 = 306
34 * 10 = 340


In [ ]:
#list:Heterogenous
l1=["apple","banana","sapota","grapes"]
for i in l1:
    print(i)

apple
banana
sapota
grapes


In [ ]:
#mutable
l1.append('@')#adds element at back of the list syntax:listname.append(element)
l1.insert(3,"hi")#adds element at particular index syntax:listname.insert(index,element)
print(l1)

['apple', 'banana', 'sapota', 'hi', 'grapes', '@', '@']


In [ ]:
#combining two lists
l2=['#',"knrvu",98,"hello"]
print(l2+l1)#use extend instead +,syntax:l1.extend(l2)

['#', 'knrvu', 98, 'hello', 'apple', 'banana', 'sapota', 'hi', 'grapes', '@', '@']


In [ ]:
l1.clear()
print(l1)


[]


In [ ]:
#pop isnused to remove particular index element
l2.pop(2)#syntax:listname.pop(index)
print(l2)

['#', 'knrvu', 'hello']


In [ ]:
#remove is used to remove particular element
l1.remove("banana")#syntax:listname.remove(element)
print(l1)

['apple', 'sapota', 'hi', 'grapes', '@', '@']


In [ ]:
#create a list of 10 integers elements print their squares save this squares in new list
l3=[4,67,56,2,88,45,767,1,33,23]
l=[]
for i in l3:
  l.append(i*i)
print(l)

[16, 4489, 3136, 4, 7744, 2025, 588289, 1, 1089, 529]


In [ ]:
#list comprehension
#newlist = [output for if ]
l3=[4,67,56,2,88,45,767,1,33,23]
l=[i*i for i in l3 if i>50]
print(l)


[4489, 3136, 7744, 588289]


In [ ]:
#take the salary from the user if salary is less than 50k 10%tax otherwise 15%tax
salary=[56000,79000,40000,120000]
l=[n-n*0.1 if n<50000 else n-n*(15/100) for n in salary]
print(l)

[47600.0, 67150.0, 36000.0, 102000.0]


In [ ]:
#create a dictionary
dict1 = {"Mentor":'Jwalitha',34:'Likitha',35:'Ramya',37:'Lavanya'}
dict1 = {"Mentor":'Jwalitha',"Mentor":'Likitha',35:'Ramya',37:'Lavanya'}
print(dict1)
print(dict1.keys())
print(dict1.values())
print(dict1[37])

{'Mentor': 'Likitha', 35: 'Ramya', 37: 'Lavanya'}
dict_keys(['Mentor', 35, 37])
dict_values(['Likitha', 'Ramya', 'Lavanya'])
Lavanya


In [ ]:
dict3 = {"Dept":"CSE","details":{"Year":"II","sec":"D","Count":71}}
print("year is",dict3["details"]["Year"])
print("sec is",dict3["details"]["sec"])
print("count is",dict3["details"]["Count"])

year is II
sec is D
count is 71


In [ ]:
l1=["fruit","vegetable","junk"]
l2=["banana","cucumber","pizza"]
dict1=zip(l1,l2)
for i in dict1:
  print(i)

('fruit', 'banana')
('vegetable', 'cucumber')
('junk', 'pizza')


In [ ]:
l1=["fruit","vegetable","junk"]
l2=["banana","cucumber","pizza"]
print(dict(zip(l1,l2)))

{'fruit': 'banana', 'vegetable': 'cucumber', 'junk': 'pizza'}


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4])#1D Array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:

B= np.array([[1,2,3,4],[4,5,6,7]])#2D Array
print(B)
print(B.ndim)
print(B.shape)

[[1 2 3 4]
 [4 5 6 7]]
2
(2, 4)


In [ ]:

C=np.array([[[1,2,34],[12,34,56]],[[11,7,9],[23,78,99]]])#3D Array
print(C)
print(C.ndim)
print(C.shape)

[[[ 1  2 34]
  [12 34 56]]

 [[11  7  9]
  [23 78 99]]]
3
(2, 2, 3)


In [ ]:
A= np.ones((3,4,2)) #Group,Row,Column
print(A)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
A= np.eye(10,10,10)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
A= np.arange(1,12,7)
print(A)
print(type(A))

[1 8]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using arange function between 1 to 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#LINSPACE-spliting a range into n numbers with common differences
A = np.linspace(12,34,12)#(lowerboundary,upperboundary,to divide equal parts)
print(A)

[12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.]


In [ ]:
#study tuple and set(day1 work)
#documentation
#qr code